# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d294c6699b8405be0e4f958da0d695c0a020ec5223faa5d5d75b741b7aadfbcc439dee2d97557c7c8d2aa196912f8226006bb552f5b6a40e2a499f0b29263b61

test:
  secret_key_base: 8f7b8827d87dafe4d1e9138984729d0631abe100ae8f53281c8d9e4e364aae62ccea48b18772f6a3a0e2bd2b4974567b72a16ac3dbe33aeed8029bf17d670ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
